
import com.cedarsoftware.util.io.*;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import ssp.seqmachine.*;

/**
 *
 * @author sergio
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form PpalFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        jButtonCreateMachine = new javax.swing.JButton();
        jButtonLoadMachine = new javax.swing.JButton();
        jButtonSaveMachine = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonAddNode = new javax.swing.JButton();
        jButtonAddNodeLink = new javax.swing.JButton();
        jButtonEditState = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        seqMachineCanvas1 = new ssp.seqmachine.ui.SeqMachineCanvas();
        jLabelStatusText = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemLoad = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SeqMachine");
        setLocation(new java.awt.Point(300, 150));

        jToolBar2.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("ToolBar.borderColor")));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jButtonCreateMachine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MachineNew.png"))); // NOI18N
        jButtonCreateMachine.setToolTipText("New Machine ...");
        jButtonCreateMachine.setFocusable(false);
        jButtonCreateMachine.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCreateMachine.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCreateMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateMachineActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonCreateMachine);

        jButtonLoadMachine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/open.png"))); // NOI18N
        jButtonLoadMachine.setToolTipText("Load Machine ...");
        jButtonLoadMachine.setFocusable(false);
        jButtonLoadMachine.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLoadMachine.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonLoadMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadMachineActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonLoadMachine);

        jButtonSaveMachine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/save.png"))); // NOI18N
        jButtonSaveMachine.setToolTipText("Save Machine ...");
        jButtonSaveMachine.setEnabled(false);
        jButtonSaveMachine.setFocusable(false);
        jButtonSaveMachine.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSaveMachine.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSaveMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveMachineActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonSaveMachine);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButtonAddNode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/StateNew.png"))); // NOI18N
        jButtonAddNode.setToolTipText("New State ...");
        jButtonAddNode.setEnabled(false);
        jButtonAddNode.setFocusable(false);
        jButtonAddNode.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAddNode.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAddNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNodeActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAddNode);

        jButtonAddNodeLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/LinkNew.png"))); // NOI18N
        jButtonAddNodeLink.setToolTipText("New link to State");
        jButtonAddNodeLink.setEnabled(false);
        jButtonAddNodeLink.setFocusable(false);
        jButtonAddNodeLink.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAddNodeLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNodeLinkActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAddNodeLink);

        jButtonEditState.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/StateEdit.png"))); // NOI18N
        jButtonEditState.setToolTipText("Edit State ...");
        jButtonEditState.setEnabled(false);
        jButtonEditState.setFocusable(false);
        jButtonEditState.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditState.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEditState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditStateActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonEditState);

        jScrollPane1.setWheelScrollingEnabled(false);

        seqMachineCanvas1.setPreferredSize(new java.awt.Dimension(640, 480));
        seqMachineCanvas1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                seqMachineCanvas1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout seqMachineCanvas1Layout = new javax.swing.GroupLayout(seqMachineCanvas1);
        seqMachineCanvas1.setLayout(seqMachineCanvas1Layout);
        seqMachineCanvas1Layout.setHorizontalGroup(
            seqMachineCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        seqMachineCanvas1Layout.setVerticalGroup(
            seqMachineCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(seqMachineCanvas1);

        jLabelStatusText.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelStatusText.setText("Sergio");
        jLabelStatusText.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jMenuItemLoad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItemLoad.setText("Load ...");
        jMenuItemLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoadActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLoad);

        jMenuItemSave.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItemSave.setText("Save");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSave);
        jMenu1.add(jSeparator1);

        jMenuSalir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit...");
        jMenu2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelStatusText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStatusText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jToolBar1, jToolBar2});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void seqMachineCanvas1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_seqMachineCanvas1PropertyChange
        switch (evt.getPropertyName()) {
            case "statusText":
                jLabelStatusText.setText(evt.getNewValue().toString());
                break;
            case "selectedNode":
                boolean v = (boolean)evt.getNewValue();
                jButtonAddNode.setEnabled(v);
                jButtonEditState.setEnabled(v);
                jButtonAddNodeLink.setEnabled(v);
                break;
            case "machineSelected":
                jButtonSaveMachine.setEnabled((boolean) evt.getNewValue());
                break;
        }
    }//GEN-LAST:event_seqMachineCanvas1PropertyChange

    private void jButtonAddNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNodeActionPerformed
        seqMachineCanvas1.createState();
    }//GEN-LAST:event_jButtonAddNodeActionPerformed

    private void jButtonCreateMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateMachineActionPerformed
        seqMachineCanvas1.createMachine();
    }//GEN-LAST:event_jButtonCreateMachineActionPerformed

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
        saveMachine();
    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    private void jMenuItemLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoadActionPerformed
        loadMachine();
    }//GEN-LAST:event_jMenuItemLoadActionPerformed

    private void jButtonAddNodeLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNodeLinkActionPerformed
        seqMachineCanvas1.createLink();
    }//GEN-LAST:event_jButtonAddNodeLinkActionPerformed

    private void jButtonLoadMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadMachineActionPerformed
        loadMachine();
    }//GEN-LAST:event_jButtonLoadMachineActionPerformed

    private void jButtonSaveMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveMachineActionPerformed
        saveMachine();
    }//GEN-LAST:event_jButtonSaveMachineActionPerformed

    private void jButtonEditStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditStateActionPerformed
        // seqMachineCanvas1.editNode();
    }//GEN-LAST:event_jButtonEditStateActionPerformed

    private void loadMachine() {
        JFileChooser dlg = new JFileChooser(System.getProperty("user.dir"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("SeqMachines", "smaq");
        dlg.setFileFilter(filter);
        int returnVal = dlg.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: "
                    + dlg.getSelectedFile().getName());
            try {
                JsonReader jsonr = new JsonReader(new FileInputStream(dlg.getSelectedFile()));
                seqMachineCanvas1.setMachine((ssp.seqmachine.SeqMachine) jsonr.readObject());
                jsonr.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    private void saveMachine() {
        JFileChooser dlg = new JFileChooser(System.getProperty("user.dir"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("SeqMachines", "smaq");
        dlg.setFileFilter(filter);
        int returnVal = dlg.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to save this file: "
                    + dlg.getSelectedFile().getName());
            try {
                HashMap options = new HashMap();
                options.put(JsonWriter.PRETTY_PRINT, true);
                JsonWriter jsonw = new JsonWriter(new FileOutputStream(dlg.getSelectedFile()), options);
                jsonw.write(seqMachineCanvas1.getMachine());
                jsonw.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddNode;
    private javax.swing.JButton jButtonAddNodeLink;
    private javax.swing.JButton jButtonCreateMachine;
    private javax.swing.JButton jButtonEditState;
    private javax.swing.JButton jButtonLoadMachine;
    private javax.swing.JButton jButtonSaveMachine;
    private javax.swing.JLabel jLabelStatusText;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemLoad;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private ssp.seqmachine.ui.SeqMachineCanvas seqMachineCanvas1;
    // End of variables declaration//GEN-END:variables
}
